tables:
  - table: sistema_informacion_gerencial.dm_area
    partitioned: false
    source_type: sql
    table_type: dimension_base
    query: |
      select
          id_area,
          area_name as cod_area,
          cod_siaf_area as area_siaf,
          area_siaf.desc_area,
          2 as nivel,
          case id_parent_area when 10468 then 10468
              else 11327 end as id_superior
      from bytsscom_bytcore.area
      inner join bytsscom_bytcore.area_siaf
          on area_siaf.cod_area = area.cod_siaf_area
      where length(area_name) = 3 and cod_siaf_area not in ('0000', '0001')
      union
      select
          id_area,
          area_name,
          cod_siaf_area,
          area_display_name,
          2 as nivel,
          case id_parent_area when 10468 then 10468
              else 11327 end as is_central
      from bytsscom_bytcore.area
      where id_parent_area = 10030 and length(area_name) = 5
      and id_area in (10383, 10390, 10395, 10385)
      union
      select
          10000 as id_area,
          '000' as cod_area,
          '0000' as cod_siaf_area,
          'UNMSM' as desc_area,
          0 as nivel,
          null as id_superior
      union
      select
          11327 as id_area,
          'D65' as cod_area,
          '0001' as area_siaf,
          'ADMINISTRACION CENTRAL' as desc_area,
          1 as nivel,
          10000 as id_superior
      union
      select
          10468 as id_area,
          'F' as cod_area,
          '1000' as area_siaf,
          'FACULTADES' as desc_area,
          1 as nivel,
          10000 as id_superior;

  - table: sistema_informacion_gerencial.dm_fuente
    partitioned: false
    source_type: sql
    table_type: dimension_base
    query: |
      select
          siaf_codigo as fuente_siaf,
          upper(desc_fuente) as desc_fuente
      from bytsscom_bytcore.fuente
      where esta_fuente = '1' and id_fuente <= 6

  - table: sistema_informacion_gerencial.dm_generica
    partitioned: false
    source_type: sql
    table_type: dimension_base
    query: |
        select
            id_clasificador as id_generica,
            cod_clasif as generica_siaf,
            nomb_clasif as desc_generica
        from bytsscom_bytcore.clasificador
        where id_nivel = 2

  - table: sistema_informacion_gerencial.hechos_institucional_consolidados
    partitioned: true
    source_type: sql
    table_type: fact
    query: |
        with certificado_anio_area as (
              select distinct
                  c.siaf_certificado,
                  cert.ano_eje,
                  a.cod_siaf_area
              from bytsscom_bytsig.vw_certificacion c
              inner join bytsscom_bytsig.memo_requerimiento m
                  on c.id_memo_requerimiento = m.id_memo_requerimiento and c.id_anio = m.id_anio
              inner join bytsscom_bytsiaf.certificado cert
                  on c.id_anio= cert.ano_eje::int and c.siaf_certificado = cert.certificado
              inner join bytsscom_bytcore.area a
                  on a.id_area = m.id_area
              where c.esta_cert = 'A' and tipo_cert = 'DP'
          ),
        clasificador as (
              SELECT DISTINCT ON (cod_clasif, codigo_siaf)
                cod_clasif,
                codigo_siaf
              FROM bytsscom_bytcore.clasificador
              WHERE codigo_siaf is not null
              ORDER BY cod_clasif, codigo_siaf
        ),
        certificado_consolidado as (
              select
                cs.ano_eje,
                cs.ano_eje||cast(cs.certificado as int)||TRIM(cf.fuente_financ)||COALESCE(SUBSTRING(cla.cod_clasif, 1, 2),'21') as id_hecho_institucional,
                cs.sec_ejec,
                cs.certificado,
                cf.fuente_financ,
                SUBSTRING(cla.cod_clasif, 1, 2) AS generica_siaf,
                sum(cm.monto_nacional) as monto_detalle
              from bytsscom_bytsiaf.certificado_secuencia cs
              inner join bytsscom_bytsiaf.certificado_fase cf
                on cs.certificado = cf.certificado
                and cs.ano_eje = cf.ano_eje
                and cs.secuencia = cf.secuencia
              inner join bytsscom_bytsiaf.certificado_meta cm
                on cs.certificado = cm.certificado
                and cs.ano_eje = cm.ano_eje
                and cs.secuencia = cm.secuencia
                and cs.correlativo = cm.correlativo
              left join clasificador cla
                on cm.id_clasificador = cla.codigo_siaf
            where cod_doc in ('086','000')  and cs.ano_eje  = __ANIO_EJECUCION__::VARCHAR
            group by cs.ano_eje, cs.sec_ejec, cs.certificado,cf.fuente_financ,SUBSTRING(cla.cod_clasif, 1, 2)
          ),
        fuentes as(
            select
                id_fuente,
                siaf_codigo,
                upper(desc_fuente) as desc_fuente
            from bytsscom_bytcore.fuente
                where esta_fuente = '1' and id_fuente <= 6
        ),
        expediente as (
             SELECT
                es.ano_eje||cast(ef.certificado as int)||ef.fuente_financ||COALESCE(SUBSTRING(c.cod_clasif, 1, 2),'21') as id_hecho_institucional,
                es.ano_eje,
                coalesce(caa.ano_eje,'0000') as area_siaf,
                es.sec_ejec,
                ef.certificado,
                ef.fuente_financ,
                coalesce(SUBSTRING(c.cod_clasif, 1, 2),'21') AS generica_siaf,
                sum(em.monto_nacional) AS monto_expediente
             FROM bytsscom_bytsiaf.expediente_secuencia es
             inner join bytsscom_bytsiaf.expediente_meta em
                on es.expediente = em.expediente
                and es.ano_eje = em.ano_eje
                and es.secuencia = em.secuencia
                and es.correlativo = em.correlativo
                and em.ciclo = 'G' and em.fase = 'D'
             inner join bytsscom_bytsiaf.expediente_fase ef
                on es.ano_eje = ef.ano_eje
                and es.expediente = ef.expediente
                and es.secuencia = ef.secuencia
                and ef.fuente_financ != '88'
             left join clasificador c
                on c.codigo_siaf = em.id_clasificador
             left join certificado_anio_area caa
                on caa.siaf_certificado = ef.certificado
                and caa.ano_eje = es.ano_eje
            WHERE es.ciclo = 'G' and es.fase = 'D' and es.ano_eje= __ANIO_EJECUCION__::VARCHAR
            group by es.ano_eje,es.sec_ejec,ef.fuente_financ,SUBSTRING(c.cod_clasif, 1, 2),caa.ano_eje,ef.certificado
        )
            SELECT
                cc.id_hecho_institucional,
                cc.ano_eje as anio,
                cc.certificado as num_certificado,
                coalesce(ex.monto_expediente,0) as monto_expediente,
                coalesce(caa.cod_siaf_area, '0000') as area_siaf,
                f.siaf_codigo as fuente_siaf,
                cc.generica_siaf,
                cc.monto_detalle as monto_certificado
            from certificado_consolidado cc
            left join certificado_anio_area caa
                on cc.certificado = caa.siaf_certificado
                and cc.ano_eje = caa.ano_eje
            inner join fuentes f
                on TRIM(cc.fuente_financ) = f.siaf_codigo
            left join expediente ex
                on cc.id_hecho_institucional = ex.id_hecho_institucional
            WHERE cc.ano_eje::integer = __ANIO_EJECUCION__;
        
  - table: sistema_informacion_gerencial.dm_certificado
    partitioned: true
    source_type: sql
    table_type: dimension
    query: |
        with certificado_anio_area as (
              select distinct
                  c.siaf_certificado,
                  cert.ano_eje,
                  a.cod_siaf_area
              from bytsscom_bytsig.vw_certificacion c
              inner join bytsscom_bytsig.memo_requerimiento m
                  on c.id_memo_requerimiento = m.id_memo_requerimiento and c.id_anio = m.id_anio
              inner join bytsscom_bytsiaf.certificado cert
                  on c.id_anio= cert.ano_eje::int and c.siaf_certificado = cert.certificado
              inner join bytsscom_bytcore.area a
                  on a.id_area = m.id_area
              where c.esta_cert = 'A' and tipo_cert = 'DP'
          ),
        certificado_consolidado as (
          select
              cc.ano_eje,
              cc.sec_ejec,
              cc.certificado,
              cc.secuencia,
              cc.correlativo,
              cod_doc,
              num_doc,
              cc.estado_envio,
              cc.estado_registro,
              fecha_creacion_clt,
              cf.glosa,
              cf.fuente_financ,
              cm.sec_func,
              cm.id_clasificador as idclasificador_siaf,
              sum(cm.monto_nacional) as monto_detalle
          from bytsscom_bytsiaf.certificado_secuencia cc
          inner join bytsscom_bytsiaf.certificado_fase cf
            on cc.certificado = cf.certificado
            and cc.ano_eje = cf.ano_eje
            and cc.secuencia = cf.secuencia
          inner join bytsscom_bytsiaf.certificado_meta cm
            on cc.certificado = cm.certificado
            and cc.ano_eje = cm.ano_eje
            and cc.secuencia = cm.secuencia
            and cc.correlativo = cm.correlativo
          where cod_doc in ('086','000')
          group by cc.ano_eje, cc.sec_ejec, cc.certificado,cc.secuencia,cc.correlativo,cf.glosa,cf.fuente_financ,cm.id_clasificador,cm.sec_func
          ),
        fuentes as(
          select
              id_fuente,
              siaf_codigo,
              upper(desc_fuente) as desc_fuente
          from bytsscom_bytcore.fuente
              where esta_fuente = '1' and id_fuente <= 6
        ),
        clasificador as (
              SELECT DISTINCT ON (cod_clasif, codigo_siaf)
                cod_clasif,
                codigo_siaf
              FROM bytsscom_bytcore.clasificador
              WHERE codigo_siaf is not null
              ORDER BY cod_clasif, codigo_siaf
        )
        SELECT
          cc.ano_eje||cast(cc.certificado as int)||f.siaf_codigo||COALESCE(SUBSTRING(cla.cod_clasif, 1, 2),'21') as id_hecho_institucional,
          cc.ano_eje as anio,
          cc.certificado as num_certificado,
          coalesce(caa.cod_siaf_area, '0000') as area_siaf,
          cc.secuencia,
          cc.sec_ejec as ejecutora,
          cc.monto_detalle as monto_clasificador,
          f.siaf_codigo as fuente_siaf,
          cc.glosa,
          cc.correlativo,
          cc.idclasificador_siaf as idclasificador_siaf,
          cla.cod_clasif AS clasificador,
          SUBSTRING(cla.cod_clasif, 1, 2) AS generica_siaf,
          cc.cod_doc,
          cc.num_doc,
          cc.estado_envio,
          cc.estado_registro,
          fecha_creacion_clt,
          mis.id_meta_institucional as idmeta,
          mis.sec_func as codmeta,
          mp.nomb_met_ins
        from certificado_consolidado cc
        left join certificado_anio_area caa
            on cc.certificado = caa.siaf_certificado
            and cc.ano_eje = caa.ano_eje
        inner join fuentes f
            on TRIM(cc.fuente_financ) = f.siaf_codigo
        inner join clasificador cla
            on cc.idclasificador_siaf = cla.codigo_siaf
        left join bytsscom_bytcore.meta_institucional_siaf mis
            on cc.sec_func = mis.sec_func and cc.ano_eje::integer = mis.id_anio
        inner join bytsscom_bytcore.meta_institucional mp
            on mis.id_meta_institucional = mp.id_meta_institucional
        WHERE cc.ano_eje::integer = __ANIO_EJECUCION__
  
  - table: sistema_informacion_gerencial.dm_expediente
    partitioned: true
    source_type: sql
    table_type: dimension
    query: |
        with clasificador as (
        SELECT DISTINCT ON (cod_clasif, codigo_siaf)
            cod_clasif,
            codigo_siaf
        FROM bytsscom_bytcore.clasificador
        WHERE codigo_siaf is not null
        ORDER BY cod_clasif, codigo_siaf
        )
        SELECT
            es.ano_eje||cast(ef.certificado as int)||ef.fuente_financ||COALESCE(SUBSTRING(c.cod_clasif, 1, 2),'21') as id_hecho_institucional,
            es.ano_eje as anio,
            es.sec_ejec as ejecutora,
            ef.expediente,
            ef.certificado,
            ef.certificado_secuencia,
            ef.fase,
            es.secuencia,
            es.correlativo,
            ef.ciclo,
            es.fecha_autorizacion,
            em.id_clasificador as idclasificador_siaf,
            c.cod_clasif AS clasificador,
            sum(em.monto_nacional) AS monto_nacional,
            es.cod_doc,
            es.num_doc,
            em.estado_envio
        FROM bytsscom_bytsiaf.expediente_secuencia es
        inner join bytsscom_bytsiaf.expediente_meta em
            on es.expediente = em.expediente
            and es.ano_eje = em.ano_eje
            and es.secuencia = em.secuencia
            and es.correlativo = em.correlativo
            and em.ciclo = 'G' and em.fase = 'D'
        inner join bytsscom_bytsiaf.expediente_fase ef
            on es.ano_eje = ef.ano_eje
            and es.expediente = ef.expediente
            and es.secuencia = ef.secuencia
            and ef.fuente_financ != '88'
        left join clasificador c
            on c.codigo_siaf = em.id_clasificador
        WHERE es.ciclo = 'G' and es.fase = 'D' and (certificado is not null) and es.ano_eje= __ANIO_EJECUCION__::VARCHAR
        group by es.ano_eje,es.sec_ejec,ef.expediente,
        ef.certificado,ef.certificado_secuencia,ef.fase,es.secuencia,es.correlativo,
        ef.ciclo,es.fecha_autorizacion,em.id_clasificador,c.cod_clasif,es.cod_doc,es.num_doc,em.estado_envio,ef.fuente_financ;

  - table: sistema_informacion_gerencial.hechos_pim
    partitioned: true
    source_type: scraper
    table_type: fact
    scraper:
      module: tasks.scrapers
      function: scrape_and_load_pim
      
  - table: sistema_informacion_gerencial.dm_pim
    partitioned: false
    source_type: sql
    table_type: dimension
    query: |
        SELECT
            id_periodo_pla as anio,
            f.siaf_codigo as fuente_siaf,
            p.id_area,
            cod_siaf_area area_siaf,
            c.id_clasificador as id_generica,
            SUBSTRING(c.cod_clasif, 1, 2) AS generica_siaf,
            sum(monto_pia) as monto_pia,
            sum(monto_pim) as monto_pim
        from bytsscom_bytpoa.vw_pim p
        inner join bytsscom_bytcore.area a
            on p.id_area = a.id_area
        inner join bytsscom_bytcore.clasificador c
            on c.id_clasificador = p.id_clasificador
        inner join bytsscom_bytcore.fuente f
            on f.id_fuente = p.id_fuente
        where not(monto_pia = 0 and monto_pim = 0) and not (id_periodo_pla=2025 and siaf_codigo = '00' and SUBSTRING(c.cod_clasif, 1, 2) ='24')
        group by id_periodo_pla,f.siaf_codigo,p.id_area,cod_siaf_area,c.id_clasificador,SUBSTRING(c.cod_clasif, 1, 2);

  - table: sistema_informacion_gerencial.dm_clasificador
    partitioned: false
    source_type: sql
    table_type: dimension
    query: |
        SELECT *
        FROM (
        SELECT DISTINCT ON (id_clasificador)
            id_clasificador as idclasificador_siaf,
            tipo_transaccion || generica AS generica,
            tipo_transaccion || generica || subgenerica || subgenerica_det || especifica || especifica_det AS clasificador,
            descripcion
        FROM bytsscom_bytsiaf.especifica_detalle
        ORDER BY id_clasificador, descripcion ,ano_eje DESC
        ) AS sub;

  - table: sistema_informacion_gerencial.dm_pim_clasificador
    partitioned: false
    source_type: sql
    table_type: dimension
    query: |
        SELECT 
            ano_eje as anio,
            fuente_financ as fuente_siaf,
            tipo_transaccion || generica as generica_siaf,
            id_clasificador as idclasificador_siaf,
            monto_asignado as monto_pim
        FROM bytsscom_bytsiaf.mpp_pca_x_especifica
        WHERE ano_eje in ('2020','2021','2022','2023','2024','2025')